### ISSUE TITLE
[BUG] Headers are not properly set up in the request

### ISSUE THREAD

**Issue by luksa3** [mysuperai/superai-sdk#84]
**Describe the bug**
Headers are not properly set up in the request, so the X-Fields header is not working

**To Reproduce**
https://github.com/mysuperai/superai-sdk/blob/a95be6ee06d1d3ad7eedb72c3d1263eb94c17578/superai/apis/project.py#L56-L58

**Expected behavior**
Add support to setup headers properly in `Client.request`.

**Versions (please complete the following information):**
 - Superai Version 0.2.1
 - Python version 3.11

**Comment by engarpe** [comment]
@lpfann can you please take a look
